package com.jjt.platform.api.admin.service;

import com.jjt.platform.api.admin.dto.ImportChildrenResponse;
import com.jjt.platform.core.domain.value.Money;
import com.jjt.platform.infrastructure.persistence.repository.ChildJpaRepository;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.IOException;
import java.io.InputStream;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Currency;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.UUID;

@Service
public class BulkChildImportService {

    private final AdminCommandService commandService;
    private final ChildJpaRepository childRepo;

    public BulkChildImportService(AdminCommandService commandService, ChildJpaRepository childRepo) {
        this.commandService = commandService;
        this.childRepo = childRepo;
    }

    @Transactional
    public ImportChildrenResponse importFromExcel(InputStream stream, UUID orgId, UUID actingUserId) throws IOException {
        List<ImportChildrenResponse.RowResult> rows = new ArrayList<>();
        Set<String> batchRollNumbers = new HashSet<>();

        int totalRows = 0;
        int importedRows = 0;
        int skippedMissingName = 0;
        int skippedMissingCampus = 0;
        int skippedDuplicateRollNumber = 0;
        int generatedRollNumbers = 0;
        int failedRows = 0;

        try (Workbook wb = new XSSFWorkbook(stream)) {
            Sheet sheet = wb.getSheetAt(0);
            int firstData = sheet.getFirstRowNum() + 1; // skip header

            for (int i = firstData; i <= sheet.getLastRowNum(); i++) {
                Row row = sheet.getRow(i);
                if (row == null || isRowEmpty(row)) continue;
                totalRows++;

                String rollNumber = cellString(row, 0);
                String fullName   = cellString(row, 1);
                String city       = cellString(row, 2);
                String campusName = cellString(row, 3);
                String schoolName = cellString(row, 4);
                String amountStr  = cellString(row, 5);
                String currency   = cellString(row, 6);

                if (fullName.isBlank()) {
                    skippedMissingName++;
                    rows.add(new ImportChildrenResponse.RowResult(i + 1, "SKIPPED", rollNumber, fullName, "Missing full name"));
                    continue;
                }
                if (campusName.isBlank()) {
                    skippedMissingCampus++;
                    rows.add(new ImportChildrenResponse.RowResult(i + 1, "SKIPPED", rollNumber, fullName, "Missing campus name"));
                    continue;
                }
                if (city.isBlank()) {
                    rows.add(new ImportChildrenResponse.RowResult(i + 1, "SKIPPED", rollNumber, fullName, "Missing city"));
                    failedRows++;
                    continue;
                }

                boolean autoGenerated = false;
                if (rollNumber.isBlank()) {
                    rollNumber = "IMP-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase();
                    autoGenerated = true;
                }

                if (batchRollNumbers.contains(rollNumber) || childRepo.existsByRollNumber(rollNumber)) {
                    skippedDuplicateRollNumber++;
                    rows.add(new ImportChildrenResponse.RowResult(i + 1, "SKIPPED", rollNumber, fullName, "Duplicate roll number"));
                    continue;
                }

                BigDecimal amount;
                try {
                    amount = amountStr.isBlank() ? BigDecimal.valueOf(5000, 2) : new BigDecimal(amountStr);
                } catch (NumberFormatException e) {
                    failedRows++;
                    rows.add(new ImportChildrenResponse.RowResult(i + 1, "FAILED", rollNumber, fullName, "Invalid education amount: " + amountStr));
                    continue;
                }

                String currencyCode = currency.isBlank() ? "PKR" : currency.trim().toUpperCase();
                try {
                    Currency.getInstance(currencyCode);
                } catch (IllegalArgumentException e) {
                    failedRows++;
                    rows.add(new ImportChildrenResponse.RowResult(i + 1, "FAILED", rollNumber, fullName, "Invalid currency: " + currencyCode));
                    continue;
                }

                try {
                    commandService.createChild(
                            rollNumber, fullName.trim(), city.trim(), campusName.trim(),
                            schoolName.isBlank() ? null : schoolName.trim(),
                            Money.of(amount, Currency.getInstance(currencyCode)),
                            UUID.randomUUID(), UUID.randomUUID(), orgId);
                    batchRollNumbers.add(rollNumber);
                    importedRows++;
                    if (autoGenerated) generatedRollNumbers++;
                    rows.add(new ImportChildrenResponse.RowResult(i + 1, "IMPORTED", rollNumber, fullName, null));
                } catch (Exception e) {
                    failedRows++;
                    rows.add(new ImportChildrenResponse.RowResult(i + 1, "FAILED", rollNumber, fullName, e.getMessage()));
                }
            }
        }

        return new ImportChildrenResponse(totalRows, importedRows, skippedMissingName, skippedMissingCampus,
                skippedDuplicateRollNumber, generatedRollNumbers, failedRows, rows);
    }

    private boolean isRowEmpty(Row row) {
        for (int c = 0; c <= 6; c++) {
            if (!cellString(row, c).isBlank()) return false;
        }
        return true;
    }

    private String cellString(Row row, int col) {
        Cell cell = row.getCell(col, Row.MissingCellPolicy.RETURN_BLANK_AS_NULL);
        if (cell == null) return "";
        if (cell.getCellType() == CellType.NUMERIC) {
            double v = cell.getNumericCellValue();
            return v == Math.floor(v) ? String.valueOf((long) v) : String.valueOf(v);
        }
        return cell.getStringCellValue().trim();
    }
}
