package com.jjt.platform.core.domain.entity;

public enum AlertType {
    PAYMENT_OVERDUE, FUND_BELOW_RESERVE, SPONSORSHIP_AT_RISK, GENERAL,
    ANOMALOUS_EXPENSE, FORECAST_SHORTFALL, DUPLICATE_EXPENSE_SUSPECT
}
